sudo: required
dist: trusty
language: cpp
compiler: gcc
cache: ccache
addons:
  postgresql: 9.4
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-locale-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libcrypto++-dev
      - libfcgi-dev
      - libmemcached-dev
      - libpqxx-dev
      - libxml2-dev
      - gcc-7
script:
  - ccache gcc-7 --version
  - ./autogen.sh
  - ./configure CC="ccache gcc-7" CXX="ccache g++-7"
  - make
  - make check
after_failure:
  - cat test-suite.log
