name: Build on Ubuntu 20.04

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
           file: docker/ubuntu/Dockerfile
           load: true
           tags: cgimap:2004
      - name: Running Docker image
        run: |
           docker run --entrypoint /bin/bash cgimap:2004 -c "/usr/local/bin/openstreetmap-cgimap --help"
